blog-laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Livewire\Volt\Volt;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Volt::route('/', 'home');

Route::view('dashboard', 'dashboard')
    ->middleware(['auth', 'verified'])
    ->name('dashboard');

Route::view('profile', 'profile')
    ->middleware(['auth'])
    ->name('profile');

require __DIR__.'/auth.php';

blog-laravel/app/Models/Fragment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Fragment extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'slug',
        'body',
        'ref_id',
    ];

    protected function title(): Attribute
    {
        return Attribute::make(
            set: fn(string $value, array $attributes) => [
                'title' => $value,
                'slug' => Str::slug($value),
            ],
        );
    }

    protected static function booted(): void
    {
        static::saving(function (Fragment $model) {
            if ($model->isDirty('slug')) {
                $count = $model->where('slug', $model->slug)->count();
                if ($count > 0) {
                    $model->slug += '-'. ($count + 1);
                }
            }
        });
    }
}

blog-laravel/app/Http/Controllers/Api/FragmentsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Jobs\CreateFragment;
use Illuminate\Http\Request;

class FragmentsController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store()
    {
        request()->validate([
            'ref_id' => ['required'],
            'title' => ['required', 'max:150'],
            'body' => ['required'],
        ]);

        CreateFragment::dispatchSync(request()->user(), request([
            'ref_id',
            'title',
            'body',
        ]));

        return response()->json([
            'msg' => 'success',
        ], 201);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

blog-laravel/app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

blog-laravel/resources/views/pages/fragments/[Fragment:slug].blade.php
<?php

use GrahamCampbell\Markdown\Facades\Markdown;
?>

<x-guest-layout>
    <section class="container mx-auto mt-8">
        <article class="bg-white">
            <h2 class="text-2xl font-bold mb-4">{{ $fragment->title }}</h2>
            {!! Markdown::convert($fragment->body)->getContent() !!}
        </article>
    </section>
</x-guest-layout>

blog-laravel/resources/views/pages/fragments/index.blade.php
<?php

use App\Models\Fragment;
use function Livewire\Volt\{state};

state([
    'fragments' => Fragment::all(),
]);

?>

<x-guest-layout>
    <section class="container mx-auto mt-8">
        @volt('fragments')
            <ul>
                @foreach ($fragments as $fragment)
                    <li wire:key="{{ $fragment->id }}">
                        <a href="/fragments/{{ $fragment->slug }}" wire:navigate class="hover:underline">{{ $fragment->title }}</a>
                    </li>
                @endforeach
            </ul>
        @endvolt
    </section>
</x-guest-layout>